/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.3/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application

    // Apply the groovy plugin to also add support for Groovy (needed for Spock)
    groovy
}

val lombokVersion by extra ("1.18.10")

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    mavenCentral()
}

dependencies {
    // Lombok
    compileOnly("org.projectlombok:lombok:${extra["lombokVersion"]}")
    annotationProcessor("org.projectlombok:lombok:${extra["lombokVersion"]}")

    // Logging
    implementation("ch.qos.logback:logback-core:1.2.3")
    implementation("ch.qos.logback:logback-classic:1.2.3")

    // Spock
    testImplementation("org.codehaus.groovy:groovy-all:2.5.6")
    testImplementation("org.spockframework:spock-core:1.2-groovy-2.5")
}
